version: "3"

services:
  backend:
    image: tsudd/student-arena-discord-bot:backend
    container_name: arenabot-backend
    user: appuser
    env_file:
      - restful_backend/prod.env
    expose:
      - 8000
    volumes:
      - ./botconfigs/:/home/appuser/project/firestore/firebase/
    command: /bin/bash -c "
      export GOOGLE_APPLICATION_CREDENTIALS="/home/appuser/project/firestore/firebase/sudent-arena-bot-firebase-adminsdk-ps8j6-7da2d15a35.json" &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"

  bot:
    image: tsudd/student-arena-discord-bot:bot
    container_name: arena-bot
    user: botuser
    env_file:
      - bot/.env
      - restful_backend/prod.env
    ports:
      - 1337:1337
    volumes:
      - ./botconfigs/:/home/botuser/project/bot/start_configs/
    depends_on:
      - backend
volumes:
  bot-db:
