version: "3"

services:
  postgresql:
    image: postgres:latest
    hostname: $${POSTGRES_HOST}
    container_name: arenabot-postgresql
    env_file:
      - postgresql/.env
    ports:
      - 5434:5432
    volumes:
      - bot-db:/var/lib/postgresql/data

  backend:
    image: arenabot-api
    container_name: django-backend
    user: appuser
    build: restful_backend/
    env_file:
      - restful_backend/.env
      - postgresql/.env
    ports:
      - 8000:8000
    volumes:
      - ./restful_backend/service/arenastatistics/:/home/appuser/project/arenastatistics
      - ./restful_backend/service/service/:/home/appuser/project/service/
      - ./restful_backend/service/firestore:/home/appuser/project/firestore/
    depends_on:
      - postgresql
    command: /bin/bash -c "
      export GOOGLE_APPLICATION_CREDENTIALS="/home/appuser/project/arenastatistics/farebase/sudent-arena-bot-firebase-adminsdk-ps8j6-7da2d15a35.json" &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"

  bot:
    image: student-arena-bot
    container_name: arena-bot
    user: botuser
    build: bot/
    env_file:
      - bot/.env
      - restful_backend/.env
      - postgresql/.env
    ports:
      - 1337:1337
    volumes:
      - ./botconfigs/:/home/botuser/project/bot/start_configs/
    depends_on:
      - postgresql
      - backend
volumes:
  bot-db:
