# Generated by Django 3.0.8 on 2021-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenastatistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontopic',
            name='emoji',
            field=models.CharField(default='🖕🏻', max_length=10, verbose_name='Topic emoji'),
        ),
    ]
