# Generated by Django 3.0.8 on 2021-05-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arenastatistics', '0002_questiontopic_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='session',
            name='dead_amount',
            field=models.IntegerField(default=0, verbose_name='Dead amount'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arenastatistics.QuestionVariant'),
        ),
    ]
