# Generated by Django 3.0.8 on 2021-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenastatistics', '0003_auto_20210519_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dis_id',
            field=models.BigIntegerField(default=228, verbose_name='User ID'),
        ),
    ]
